### ISSUE TITLE
comment.content_object is None on comment_will_be_saved signal

### ISSUE THREAD

**Issue by JanMalte** [danirus/django-comments-xtd#33] opened 2016-03-29 12:48 UTC
The value of the GeneriRelation `comment.content_object` is always `None`, on the comment app signals.

This only happens if `django-comments-xtd` is in `INSTALLED_APPS`. Removing it will result in the correct related object instance.

**Comment by danirus** [comment] 2016-03-29 12:58
Hi @JanMalte, could you tell me the steps to reproduce the error. I have fixed a number of bugs in the version under development (branch develop) but I don't get to remember this one. Let me know the details and I will be glad to look into it.

**Comment by JanMalte** [comment] 2016-03-30 08:28
Here some snippets of my code

```python
#project/settings.py
# ...
INSTALLED_APPS = (
    # ...
    'django_comments',
    'django-comments-xtd',  # If removed, the output in parse_mention_in_comment()
                            # will be the correct content _object
    # ...
)
# Comments
SITE_ID = 1
COMMENTS_APP = "django_comments_xtd"
COMMENTS_XTD_CONFIRM_EMAIL = False
# ...
```

```python
#reactions/apps.py
class ReactionsConfig(AppConfig):
    def ready(self):
        from reactions.signals import parse_mention_in_comment
        from django_comments.signals import comment_was_posted
        comment_was_posted.connect(parse_mention_in_comment)
```

```python
#reactions/signals.py
def parse_mention_in_comment(sender, comment, request, **kwargs):
    print(comment.content_object)  # Output: None
```

**Comment by danirus** [comment] 2016-04-01 08:36
At the time the signal `comment_was_posted` is triggered, django-comments-xtd sends the comment embedded in a URL to the user by email. The comment didn't hit the DB yet, it's merely a dictionary. That's why there's no content_object in the comment. 

You could catch the proper comment object once the user has confirmed the comment, that happens right after the user clicks on the link received by email. django-comments-xtd sends the signal `confirmation_received`. It's defined in `django_comments_xtd.signals`. I documented it a bit [here](http://django-comments-xtd.readthedocs.org/en/latest/tutorial.html#signal-and-receiver).

What exactly is what you want to do?

**Comment by JanMalte** [comment] 2016-04-01 19:26
My goal is, to catch the creation of a comment to take further actions.
Maybe I would have to connect to the pre_save signal of a comment instead.

I thought the described workflow doesn't apply for the stated setting, as there is no email confirmation?
`COMMENTS_XTD_CONFIRM_EMAIL = False`

**Comment by danirus** [comment] 2016-04-02 06:53
There's no confirmation email if `COMMENTS_XTD_CONFIRM_EMAIL = False`, but still, the comment object coming to the receivers of `comment_was_posted` is still a `TmpXtdComment`. If you need to change content or look at content, you can do it in that object as you would do it in the `XtdComment`. It has all the attributes of a `Comment` and those you could have added with your own model: `comment.comment`, `comment.submit_date`, `comment.ip_address`, etc.

If you want to decide on whether to drop the comment maybe `comment_will_be_posted`, might be better choice. It's sent before `comment_was_posted`. If your receiver for `comment_will_be_posted` returns `False` the comment will be dropped so won't make it for the database neither. 

If you don't need comment confirmation by email and neither nested comments, maybe your app would be perfectly fine with the django-comments app.

**Comment by danirus** [comment] 2016-04-02 07:01
I close the issue, as it's not a bug but a design decision.
I leave the conversation open.

**Closed by danirus** 2016-04-02 07:01 UTC
