### ISSUE TITLE
Invalid comment form raises ValueError

### ISSUE THREAD

**Issue by ashwani99** [danirus/django-comments-xtd#170] opened 2020-06-22 01:37 UTC
When using the Web API for creating new comments, the serializer `django_comments_xtd.api.serializers.WriteCommentSerializer.save()` raises a `ValueError` for invalid forms

```ValueError("get_comment_object may only be called on valid forms") ```

This happens due to the behaviour of [django_comments.forms.CommentSecurityForm.py](https://github.com/django/django-contrib-comments/blob/4c5c5d00eba6fd4f02cf0ebae90c81f5fd19377d/django_comments/forms.py#L118)

**Comment by danirus** [comment] 2020-07-11 16:17
Yes, I'm afraid it works that way. when I wrote the API I didn't think on providing a full-featured API but one to fulfil the requirements of the JavaScript Plugin. As you found out, the `CommentSecurityForm` is the way to avoid form tampering. It's in my roadmap to provide a better web API for the app.

**Comment by danirus** [comment] 2020-07-11 16:17
Duplicate of #155

**Comment by ashwani99** [comment] 2020-07-11 19:05
@danirus Yes it works that way. But since `django-comments-xtd`'s API endpoints are on top of `django-comments`, so instead of propagating the exception, we can also simple reject the comment with a HTTP 403 response.

I would be happy to send a PR for this. But what's you view on this?

**Comment by danirus** [comment] 2020-07-12 13:28
Yes, a HTTP 403 would have been the right response should the comment be rejected. But I want to allow it.
My view on this is that django-comments-xtd must provide a complete web API, allowing also posting comments. That means circumventing the issue with the security form only when using the web API.

Thank you for your willing to help @ashwani99, there are a few tickets labeled as bug, enhancement or feature that you could work on and send a PR. Take a look and let me know if there's something you would like to work on. I'm already working on the issue #155 .

**Comment by ashwani99** [comment] 2020-07-12 13:41
That would be great. Currently, the API is only usable with the forms and is not a frontend agnostic solution. I will look for other issues to work on :)

**Closed** 2020-07-12 14:09 UTC
Labels: documentation, duplicate, feature
