### ISSUE TITLE
initialize_nested_count when run in a migration can result in schema errors

### ISSUE THREAD

**Issue by jxcl** [danirus/django-comments-xtd#271] opened 2021-01-28 15:59 UTC
Since django-comments-xtd runs a management command that looks at the schema outside of the current migration it's running, it's possible for it to see a schema state that is not the same as the state the schema editor is in. 

In my case, when migrating from an empty database, the `django_comments_xtd.0008_auto_20200920_2037` migration was run before all of my user model migrations, causing `initialize_nested_count` to inspect my user model and try to access columns on the database that were not there. 

This can be solved by specifying `run_before` in the user model migrations, but it would be nice if that were not necessary. It would be better to find a way to populate the nested count outside of a migration, or else have a separate command that utilizes the model state in the migration rather than the model state derived from the codebase.

Thanks!

**Comment by danirus** [comment] 2021-01-29 16:43
Thank you for your report.
I can't figure how can `initialize_nested_count` inspect your user model.
Could you please, make a repository with the code? I would like to see it in detail.

**Comment by danirus** [comment] 2021-02-28 10:02
I finally reproduced the error. The management command `initialize_nested_count` does inspect the user model, but only explicitly. `user` is an attribute of the model tree of which `XtdComment` is part of. The problem is indeed as you mention, that the user model, whatever it is, is not yet reflected in the DB as defined in code, at the moment the migration 0008 tries to run. Thank you again for the report.

**Comment by danirus** [comment] 2021-02-28 14:55
The fix has been merged in master. The solution consist of not running the management command in association with the migration 0008. Django developers who want to use the nested_count attribute can run the command manually. I have added a new section in [the documentation](https://django-comments-xtd.readthedocs.io/en/latest/management.html) to explain the `initialize_nested_count`.

**Closed by danirus** 2021-02-28 14:55 UTC
Labels: bug
